name: Deploy React App from GitHub to AWS Elastic Beanstalk
on:
  # activates the workflow when there is a push on the master branch
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest # the operating system your job should run on
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Latest Repo
        # checks out your repository under the GitHub workspace so that your workflow can access it
        uses: actions/checkout@master

      - name: Generate Deployment Package 
        # zip all files except .git
        run: zip -r deploy-dog-app.zip * -x "**node_modules**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          # replaces '[:\.]+' in the timestamp with '-'
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
         #  input the  credentials you used to setup AWS CLI and credentials for the application environment
          aws_access_key: "${{ secrets.ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.SECRET_ACCESS_KEY }}"
          application_name: react-app
          environment_name: react-app-dev
          version_label: "${{ steps.format-time.outputs.replaced }}"
          region: us-west-1
          deployment_package: deploy-dog-app.zip

      - name: Deployed!
        run: echo App deployed to ELB



        # access key = AKIA4JYCHQNH2L4VNQRZ
        # secret = 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

        # 2 access key = AKIA4JYCHQNHYB2NE6UN
        # 2 secret key = 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